
-- CourseCart - Learning Materials E-commerce Platform
-- Keep original table structure, only replace products table data with study-related products

-- Clear existing product data (if exists)
TRUNCATE TABLE public.products RESTART IDENTITY CASCADE;

-- Insert new study-related product data
INSERT INTO public.products (product_id, name, slug, price, description, image_url) VALUES
                                                                                        (1, 'Programming Laptop', 'programming-laptop', 899.99, 'High-performance laptop for programming, 16GB RAM, 512GB SSD, perfect for running development environments and virtual machines.', 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop'),
                                                                                        (2, 'Mechanical Keyboard', 'mechanical-keyboard', 129.99, 'Blue switch mechanical keyboard with RGB backlighting, designed for comfortable coding sessions.', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=300&fit=crop'),
                                                                                        (3, 'Adjustable Standing Desk', 'standing-desk', 399.99, 'Electric height-adjustable desk with memory settings, improves posture during long study hours.', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop'),
                                                                                        (4, 'Algorithms Textbook', 'algorithms-book', 49.99, 'Classic textbook on algorithms and data structures with implementations in Python and JavaScript.', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop'),
                                                                                        (5, 'Git Mastery Course', 'git-course', 29.99, 'Complete version control course covering Git basics, GitHub collaboration, and team development best practices.', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=300&fit=crop'),
                                                                                        (6, 'Full Stack Web Development', 'web-dev-course', 79.99, 'Complete web development course from HTML/CSS to React/Node.js with real-world projects.', 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=400&h=300&fit=crop'),
                                                                                        (7, 'Programmer Coffee Mug', 'programmer-mug', 19.99, 'Large insulated coffee mug with "Hello World" print, keeps drinks warm during coding sessions.', 'https://images.unsplash.com/photo-1561047029-3000c68339ca'),
                                                                                        (8, 'Noise Cancelling Headphones', 'noise-headphones', 199.99, 'Active noise cancellation headphones for focused studying in noisy environments.', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop'),
                                                                                        (9, 'External Monitor 4K', 'external-monitor', 249.99, '27-inch 4K monitor with IPS panel, perfect for multitasking programming and design work.', 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=300&fit=crop'),
                                                                                        (10, 'Python Programming Course', 'python-course', 34.99, 'Beginner to advanced Python programming course covering data analysis, automation, and web development.', 'https://images.unsplash.com/photo-1542831371-29b0f74f9713'),
                                                                                        (11, 'Programmer Hoodie', 'programmer-hoodie', 39.99, 'Comfortable hoodie with coding-themed design, perfect for late-night study sessions.', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop'),
                                                                                        (12, 'Database Design Book', 'database-book', 44.99, 'Comprehensive guide to database design, SQL optimization, and data modeling techniques.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=300&fit=crop'),
                                                                                        (13, 'Wireless Mouse', 'wireless-mouse', 29.99, 'Ergonomic wireless mouse with programmable buttons for efficient workflow.', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop'),
                                                                                        (14, 'React.js Course', 'react-course', 54.99, 'Complete React.js course with hooks, context API, and modern frontend development practices.', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=300&fit=crop'),
                                                                                        (15, 'Laptop Backpack', 'laptop-backpack', 59.99, 'Water-resistant backpack with padded laptop compartment and organized pockets for tech accessories.', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop'),
                                                                                        (16, 'JavaScript Mastery', 'javascript-course', 39.99, 'Deep dive into JavaScript fundamentals, ES6+ features, and modern web development patterns.', 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop'),
                                                                                        (17, 'Desk Lamp', 'desk-lamp', 34.99, 'Adjustable LED desk lamp with multiple brightness levels for optimal study lighting.', 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop'),
                                                                                        (18, 'Mobile App Development', 'mobile-app-course', 69.99, 'Learn to build cross-platform mobile applications using React Native or Flutter.', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop'),
                                                                                        (19, 'Notebook Set', 'notebook-set', 24.99, 'Set of 3 premium notebooks for note-taking, planning, and sketching ideas.', 'https://images.unsplash.com/photo-1568667256549-094345857637?w=400&h=300&fit=crop'),
                                                                                        (20, 'Cloud Computing Course', 'cloud-course', 89.99, 'Learn AWS, Azure, and Google Cloud Platform fundamentals for modern application deployment.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop');

-- Note: All other table structures and relationships remain unchanged
-- The foreign key constraints will continue to work with the new product data
